swagger: '2.0'
info:
  description: AUTO.RIA
  version: 1.0.0
  title: Информация по id объявления
  contact:
    email: denys.bedrii@ria.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: developers.ria.com
basePath: /auto
schemes:
  - https
paths:
  /info:
    get:
      tags:
        - AUTO info
      summary: по id объявления
      operationId: Descriptionsearch
      description: >
        **info** — название метода API, к которому Вы хотите обратиться.
        **API_KEY** — ключ доступа. Для получения  доступа нужно
        зарегестрироватся на портале *developers.ria.com*
        **auto_id** — номер объявления по которому нужна информация
      parameters:
        - in: query
          name: auto_id
          description: ''
          required: true
          type: number
      produces:
        - application/json
      responses:
        '200':
          description: search results
        '400':
          description: bad input parameter
        '404':
          description: NOT_FOUND
        '429':
          description: OVER_RATE_LIMIT
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
